# Generated by Django 5.0.2 on 2024-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('training_id', models.IntegerField(default=0)),
                ('training_name', models.CharField(max_length=100)),
                ('training_description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
